version: '3.7'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gorm
      PGPASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
  frontend:
    build:
      context: frontend/
      # For development only build up to build-stage
    ports:
      - '8080:8080'
    # Mount to enable hot reload
    volumes:
      - './frontend:/app'
      - /app/node_modules
  backend:
    build:
      context: backend/
      target: build-stage
    depends_on:
      - postgres
    ports:
      - '5000:5000'
    volumes:
      - './backend:/app'
    environment:
      - SPOTIFY_ID=e9eb61d2a082412caa493f4c9ef86774
      - SPOTIFY_SECRET=681d8d66ad6945faa5f3b3ca9ac5559e
  sass:
    image: danmaq/ruby-sass
    volumes:
      - './frontend:/app'
    # Watch for changes to the sass folder and recompile sass on any changes
    command: sass --style compressed --watch /app/src/sass/bulma.scss:/app/public/main.css
  omnidb: # workbench for inspecting database
    image: taivokasper/omnidb
    ports:
      - '9876:8080'
      - '25482:25482' # Web socket
    volumes:
      - omnidb:/etc/omnidb
  sass:
    image: danmaq/ruby-sass
    volumes:
      - .:/code
    # Watch for changes to the sass folder and recompile sass on any changes
    command: sass --style compressed --watch /code/frontend/sass/bulma.scss:/code/frontend/public/global.css

volumes:
  postgres:
  omnidb:
