version: '3.7'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    depends_on:
      - postgres
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: my-secret-0000
        port: 4466
        databases:
          default:
            rawAccess: true
            connector: postgres
            migrations: true
            host: postgres
            port: 5432
            user: prisma
            password: prisma
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data
  frontend:
    build:
      context: frontend/
      # For development only build up to build-stage
      target: build-stage
    ports:
      - '8080:8080'
    # Mount to enable hot reload
    volumes:
      - './frontend:/app'
  backend:
    build:
      context: backend/
      target: build-stage
    depends_on:
      - prisma
    ports:
      - '5000:5000'
    volumes:
      - './backend:/app'
    environment:
      - SPOTIFY_ID=e9eb61d2a082412caa493f4c9ef86774
      - SPOTIFY_SECRET=681d8d66ad6945faa5f3b3ca9ac5559e
  sass:
    image: danmaq/ruby-sass
    volumes:
      - './frontend:/app'
    # Watch for changes to the sass folder and recompile sass on any changes
    command: sass --style compressed --watch /app/src/sass/bulma.scss:/app/public/main.css
volumes:
  postgres: 
