version: '3.7'

services:
  postgres:
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gorm
      PGPASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data
  frontend:
    build:
      context: frontend/
      # For development only build up to build-stage
  backend:
    build:
      context: backend/
      target: build-stage
    depends_on:
      - postgres
    volumes:
      - './backend:/app'
    environment:
      - SPOTIFY_ID=e9eb61d2a082412caa493f4c9ef86774
      - SPOTIFY_SECRET=681d8d66ad6945faa5f3b3ca9ac5559e
  omnidb: # workbench for inspecting database
    image: taivokasper/omnidb
    ports:
      - '9876:8080'
      - '25482:25482' # Web socket
    volumes:
      - omnidb:/etc/omnidb
  proxy:
    hostname: proxy
    build: proxy/
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
      - frontend

volumes:
  postgres:
  omnidb:
