version: '3.7'

services:
  frontend:
    build:
      target: production-stage
    command: 
  backend:
    build:
      target: production-stage
    environment:
      - RETURN_STACKTRACE=true
  proxy:
    build:
      args:
        config: prod.conf
